#!/usr/bin/perl
#-*-Perl-*-

#--------------------------------------------------------#
$description =
"Syntax: sscan [options] [file...]

Sscan produces a metrical analysis of a Sanskrit text
in the CSX encoding. Heavy syllables are represented
in the output by \"-\", light syllables by \"u\". The
program understands the conventions regarding comments,
prose passages, \"X uv‡ca\"-type lines and non-anu˘Òubh
lines employed in the CSX versions of the Mah‡bh‡rata
and R‡m‡yaıa; it can also cope with the Alsdorf and
metrically emended versions of the RV text. It should
produce good results on other texts too, provided that
they are laid out in a fairly normal way.

-h option prints this help.
";
#--------------------------------------------------------#

require 'getopts.pl';
Getopts(':h');
if ($opt_h) {
    print STDERR $description;
    exit 1;
}

$cons  = "¸ß˛kgÔcj§ÒÛ◊ıtdnpbmyrlv˜˘sh";
$stop  = "kgcjÒÛ◊tdpb";
$svow  = "a†Öi°çãu£óÅÁ∆«ÎÏ";			# "Ï" for "Î acute" in RV
$lvow  = "‡µ∂„∑∏ÂΩæÈœeÇäo¢ïE";
$vowel = "$svow$lvow";

while (<>) {
    next if (/^\d{8}[ A-Z] /);				# MBh uvaaca, prose
    if (($num, $line) = /^(\d+[^ ]* +)(.*)$/s) {	# Line numbers
	$_ = $line;
    }
    else {
	print "\n" if /^$/;
	next;
    }
    s/([$vowel])Î/$1Û/g;			# Consonantal "Î"
    s/a[i°çu£ó]/E/g;				# 2-letter vowels
    tr/- '3*Æ//d;				# Punctuation, space, pluta
    tr/Ø/./;					# Occurs for "." in RV
    s/\./. /g;					# Syllabic "rest" in RV
    s/[–—“”‘ÿŸ⁄‹›≥]/aa/g;			# Disyllabic vowels in RV
    s/([$stop])h/$1/g;				# 2-letter consonants
    s/(^|[| ])[$cons]+/$1/g;			# Initial consonants
    s/[$lvow][$cons]*(;?)[$cons]*/- $1/g;	# V
    s/[$svow][$cons]{2,};[$cons]*/- ;/g;	# vCC;
    s/[$svow][$cons];[$cons]+/- ;/g;		# vC;C
    s/[$svow](;?)[$cons]{2,}/- $1/g;		# vCC (includes v;CC)
    s/[$svow][$cons]*(;?)[$cons]*/u $1/g;	# vC  (includes v;C, vC;)
    s/ $//;					# Tidy up
    s/([;|])([^|])/$1 $2/g;
    print $num, $_;
}
